package com.example.vconsol_flutter_library.utils

object Events {
    const val ON_AUDIO_LIST = "tst.vconsol/onAudioList"
    const val ON_BREAKOUT_JOIN_INVITATION_BY = "tst.vconsol/onBreakoutJoinInvitationBy"
    const val ON_BREAKOUT_RECALL = "tst.vconsol/onBreakoutRecall"
    const val ON_BREAKOUTROOM_END = "tst.vconsol/onBreakoutRoomEnd"
    const val ON_CHAT = "tst.vconsol/onChat"
    const val ON_COHOST_TOKEN = "tst.vconsol/onCoHostToken"
    const val ON_CONFERENCE_INFO = "tst.vconsol/onConferenceInfo"
    const val ON_CONFERENCE_INFO_UPDATE = "tst.vconsol/onConferenceInfoUpdate"
    const val ON_CONFERENCE_LOCKED = "tst.vconsol/onConferenceLocked"
    const val ON_CONNECTION_SUCCESS = "tst.vconsol/onConnectionSuccess"
    const val ON_CONTENT = "tst.vconsol/onContent"
    const val ON_CONTENT_PERMISSION_RESULT = "tst.vconsol/onContentPermissionResult"
    const val ON_CONTENT_REQUEST = "tst.vconsol/onContentRequest"
    const val ON_CONTENT_SETTINGS_CHANGED = "tst.vconsol/onContentSettingsChanged"
    const val ON_CONTENT_SHARE_REQUEST = "tst.vconsol/onContentShareRequest"
    const val ON_COWATCH_EVENTS = "tst.vconsol/onCowatchEvents"
    const val ON_CUSTOM_CONFERENCE_EVENT = "tst.vconsol/onCustomConferenceEvent"
    const val ON_CUSTOM_CONFERENCE_EVENTS = "tst.vconsol/onCustomConferenceEvents"
    const val ON_EXITED = "tst.vconsol/onExited"
    const val ON_INTERNAL_RECONNECTION = "tst.vconsol/onInternalReconnection"
    const val ON_KICKEDOUT = "tst.vconsol/onKickedOut"
    const val ON_LAYOUT_CHANGED = "tst.vconsol/onLayoutChanged"
    const val ON_LIBRARY_INITLIZED = "tst.vconsol/onLibraryInitlized"
    const val ON_MODE_CHANGE = "tst.vconsol/onModeChange"
    const val ON_MULTIBROADCAST_LIST = "tst.vconsol/onMultiBroadcastList"
    const val ON_MULTIBROADCAST_STATUS = "tst.vconsol/onMultiBroadcastStatus"
    const val ON_MUTEALL = "tst.vconsol/onMuteAll"
    const val ON_MUTE_FROM_REMOTE = "tst.vconsol/onMuteFromRemote"
    const val ON_PARTICIPANT_STATUS = "tst.vconsol/onParticipantStatus"
    const val ON_PARTICIPANTS = "tst.vconsol/onParticipants"
    const val ON_PENDING_ACCEPT = "tst.vconsol/onPendingAccept"
    const val ON_QUALITY_UPDATE = "tst.vconsol/onQualityUpdate"
    const val ON_RECORD = "tst.vconsol/onRecord"
    const val ON_REVOKE_CONTENT_PERMISSION = "tst.vconsol/onRevokeContentPermission"
    const val ON_RTMP = "tst.vconsol/onRtmp"
    const val ON_SMART_APP_EVENT = "tst.vconsol/onSmartAppEvent"
    const val ON_USER_PINNED = "tst.vconsol/onUserPinned"
    const val ON_USER_SPEAKS = "tst.vconsol/onUserSpeaks"
    const val ON_WEBINAR_STARTED = "tst.vconsol/onWebinarStarted"
    const val ON_WEBINAR_STOPED = "tst.vconsol/onWebinarStoped"
    const val ON_WHITE_BOARD_INIT = "tst.vconsol/onWhiteBoardInit"
    const val ON_WHITE_BOARD_ONCHANGE = "tst.vconsol/onWhiteBoardOnChange"
    const val ON_WHITE_BOARD_VOLATILE_CHANGE = "tst.vconsol/onWhiteBoardVolatileChange"
    const val RECONNECT_AND_JOIN_TO_BREAKOUTROOM = "tst.vconsol/reconnectAndJoinToBreakoutRoom"
    const val RECONNECT_MEETING = "tst.vconsol/reconnectMeeting"

}